version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ambiente-php-mysql
    container_name: ambiente-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - rede-ambiente

  db:
    image: mysql:5.7
    container_name: ambiente-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'ambiente'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_PASSWORD: '123'
      MYSQL_USER: 'root'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - rede-ambiente

  nginx:
    image: nginx:alpine
    container_name: ambiente-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - rede-ambiente

networks:
  rede-ambiente:
    driver: bridge

volumes:
  dbdata:
    driver: local